MODULES=(
	videocc_sm8550
	dispcc_x1e80100
	gpucc_x1e80100
	phy_qcom_edp
	panel_samsung_atna33xc20
	msm
	tcsrcc_x1e80100
	phy_qcom_qmp_pcie
	phy_qcom_qmp_usb
	phy_qcom_qmp_usbc
	phy_qcom_eusb2_repeater
	phy_snps_eusb2
	phy_qcom_qmp_combo
	surface_hid
	surface_aggregator
	surface_aggregator_registry
	surface_aggregator_hub
	isofs
	squashfs
	overlay
	usb_storage
	uas
)
BINARIES=()
FILES=()
HOOKS=(base udev sp11plymouth block keyboard filesystems sp11live)
COMPRESSION="zstd"
COMPRESSION_OPTIONS=(-19)
