#!/usr/bin/env bash

build() {
	add_module loop
	add_module squashfs
	add_module overlay
	add_module iso9660
	add_module usb_storage
	add_module uas
	add_module videocc_sm8550
	add_runscript
}

help() {
	cat <<HELPEOF
Mount the SP11 live-image SquashFS from removable media and place a volatile
tmpfs overlay above it.
HELPEOF
}
